[WIP]💄 Config eslint and prettier
canhnd58/achromevement pull request #20
Opened 2018-10-22 18:00 UTC by tung-eh

Closes https://github.com/canhnd58/achromevement/issues/1

## Proposed Changes

  - Add prettier
  - Update .eslintrc
  -

2018-10-22 18:07 UTC, canhnd58 requested changes

2018-10-22 18:07 UTC, canhnd58 commented on package.json
>      "eslint-config-standard": "^12.0.0",
Remove dependency if no longer used

2018-10-22 18:13 UTC, canhnd58 requested changes
Update doc/coding_style.md to specify how to format files or which command to run before submitting codes.

2018-10-23 01:13 UTC, tung-eh commented
Close due to duplicate

2018-10-23 01:13 UTC, closed without merging

2018-10-23 03:36 UTC, canhnd58 commented
Create a feature request if you still want this to be included