💅 Add prettier
canhnd58/achromevement pull request #30
Opened 2018-10-26 16:19 UTC by tung-eh

Closes https://github.com/canhnd58/achromevement/issues/25

## Proposed Changes

  - Add `prettier` and config to work with `eslint`
  - Add script to format code using prettier
  - Fix all the wrong format in files

2018-10-26 16:55 UTC, canhnd58 requested changes

2018-10-26 16:55 UTC, canhnd58 commented on package.json
> +    "format": "prettier --write *.js"
The command `npm run format` seems to format only js files directly under the project root folder.
<img width="408" alt="screen shot 2018-10-26 at 23 52 18" src="https://user-images.githubusercontent.com/9996596/47580859-31d3c600-d97a-11e8-9d2d-c09640eaeb72.png">

2018-10-27 03:24 UTC, tung-eh commented on package.json
> +    "format": "prettier --write *.js"
Fixed. Thank you

2018-10-27 03:48 UTC, canhnd58 approved these changes

2018-10-27 03:48 UTC, merged